---
- name: Install lighthouse dependency 
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighthouse copy from git
  git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dest }}"
- name: Lighthouse create config
  become: true
  template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: reload-nginx
